- name: basicVLAN Config
  hosts: AristaSW

  gather_facts: false
  connection: network_cli

  tasks:
  - name: Basic Configuration
    eos_command:
     commands: configure terminal, vrf instance GT111, vlan 333
  - name: Basic2 Configuration
    eos_command:
     commands: configure terminal, vrf instance GT222, vlan 222
