- name: basicVLAN Config
  hosts: AristaSW

  gather_facts: false
  connection: network_cli

  tasks:
  - name: Basic Configuration
    eos_command:
     commands: configure terminal, vrf instance GT300, vlan 300
  tasks:
  - name: Basic2 Configuration
    eos_command:
     commands: configure terminal, vrf instance GT200, vlan 200
